### ISSUE TITLE
kernel size in GhostModule

### ISSUE THREAD

**Issue by tyziaaaa** [huawei-noah/CV-Backbones#36]
Good Work! Thanks for sharing.
Why is the kernel size in primary_conv 1 and this in cheap_operation 3(dw) ? If you have tried setting the kernel size in primary 3 and in cheap_operation 1(dw)? It seems that the latter has less FLOPs. (Although I guess this adjustment may lead to worse behavier.)

**Comment by iamhankai** [comment]
Not yet. You can try this setting. I'm also interested in it.
