### ISSUE TITLE
Employing GhostNet with HRNet-w32

### ISSUE THREAD

**Issue by devshree07** [huawei-noah/CV-Backbones#59]
I was working on a research-based project in which I had to create a light-weight model for human pose estimation. I came across GhostNet and wanted to combine it with HRNet-w32. Can you provide some insights on the same? It would be really helpful. Thank you in advance.

**Comment by iamhankai** [comment]
In HRNet, the downsampled path may be viewed as a ghost of the high-resolution path. It's a potential direction.
