### ISSUE TITLE
I have a question about ghostNet.py

### ISSUE THREAD

**Issue by Yukimori-GitHub** [huawei-noah/CV-Backbones#64]
link：https://github.com/huawei-noah/CV-Backbones/blob/master/ghostnet_pytorch/ghostnet.py
  I am a beginner of deep learning, and I have read the paper of GhostNet. When I am reading the ghostNet.py, I cannot understand the code in line: 121-125. Of course, I knew what is Squeeze-and-excitation, but I do not know the mean of se_ratio.
  Why this parameter should be needed, Why and When should I use it to activate the module of Squeeze-and-excitation? I cannot find any answers about this parameter, and hoping you can answer this question. 
  I am looking forward to your answer. Thank you!

**Comment by iamhankai** [comment]
se_ratio is the reduction ratio in SENet paper. When se_ratio=0, it means we do not use SE module in this block.
