### ISSUE TITLE
RuntimeError: Function 'BmmBackward0' returned nan values in its 0th output.

### ISSUE THREAD

**Issue by onlinehuazai** [huawei-noah/CV-Backbones#66]
经常碰到backward错误，还是各种不同的错误，但是单卡好像没什么问题，多卡不管是DP还是DDP都会报这个错误

**Comment by iamhankai** [comment]
这是跑哪个代码？

**Comment by onlinehuazai** [comment]
> 这是跑哪个代码？

https://github.com/huawei-noah/CV-Backbones/blob/master/tnt_pytorch/tnt.py

大佬，跑的TNT代码

**Comment by iamhankai** [comment]
有更完整的log吗
