### ISSUE TITLE
Inquiry into 'feature_only' setting in timm

### ISSUE THREAD

**Issue by yorklyb** [huawei-noah/CV-Backbones#67]
Hi Kai Han. We are trying to introduce ghostnet backbone from timm: https://github.com/rwightman/pytorch-image-models/tree/master/timm

When we set feature_only as true, the structures after block 7 are ignored. The backbone works well but we are wondering if this is normal? Why these layers are abandoned?
![ghost 2305843009236165318](https://user-images.githubusercontent.com/58899542/129074169-fd6286cb-62d9-4b00-a2db-88a433eee1dc.png)

**Comment by iamhankai** [comment]
It's not normal. You should modify `feature_cfg['out_indices']` to get which layers as your outputs.
