### ISSUE TITLE
is GhostNet supported in Tensorflow 2.x, if yes how i can train and fit the model ?

### ISSUE THREAD

**Issue by jonathantanuwijaya** [huawei-noah/CV-Backbones#71]

**Comment by iamhankai** [comment]
Thanks for the attention. GhostNet is developed on TF 1.x and Pytorch. We do not have plan to support TF 2.x. Sorry for that.

A thirdparty of TF 2.x implementation may be helpful for you: https://github.com/CarloLepelaars/ghostnet_tf2
