### ISSUE TITLE
How to use GhostNet models like model.fit, model.evaluate, and model.predict ?

### ISSUE THREAD

**Issue by YMasterous** [huawei-noah/CV-Backbones#72]
I want to input data `x_train`, `y_train`, `x_test`, and `y_test` on GhostNet models and will train model like `model.fit`, test model like `model.evaluate`, and `model.predict`. Please help.

**Comment by iamhankai** [comment]
These thirdparty implementations may be helpful for you: 
- TF1.x: https://github.com/YeFeng1993/GhostNet-Keras
- TF2.x: https://github.com/CarloLepelaars/ghostnet_tf2
