### ISSUE TITLE
About PATM class of Wave_MLP.py

### ISSUE THREAD

**Issue by ysj9909** [huawei-noah/CV-Backbones#85]
self.tf_h computes x_h * cos(theta_h), x_h * sin(theta_h) features separately.
However, according to the formula in the paper, I think that to add the above two features, they must be calculated together. Isn't the code wrong?

**Comment by yehuitang** [comment]
'self.theta_h' takes 'x' as input and outputs the phase 'theta'.  They are calculated together.  What is the meaning of  'computes features separately' in your question?

**Comment by ysj9909** [comment]
Self.tfc_h outputs conv output in dim groups. At this time, if you look at equation 9 in the paper, isn't it a function intended to be calculated together by grouping groups as x_h * cos(theta_h) + x_h*sin(theta_h)? However, that operation is not possible with self.tfc_h.
In summary, in my opinion, self.tfc_h is a convolution of depth 2, not an mlp operation.

**Comment by yehuitang** [comment]
The input and output sizes of 'self.tfc_h' are 2*dim and dim, which aims to aggregate two groups of features with weights. Besides, the impact of the local window is also discussed in the paper.

**Comment by zhonghaochen** [comment]
Hello, 
I have a similar question. As the Eqn. 7-9 indicated that the real and imaginary parts are added to get the output. However, in the provided source code, they are concatenated in the channel dimension. That is confusing.
