### ISSUE TITLE
ISSUE about: WaveMLP train time 

### ISSUE THREAD

**Issue by discaptain** [huawei-noah/CV-Backbones#86]
I installed your torch version (using apex), and used your train script. But I got a long long train time of each iteration. 
This is my train time.  Your train logs show the time about 0.5s. 
`Train: 0 [ 150/1251 ( 12%)]  Loss:  6.914239 (6.9164)  Time: 1.082s,  946.45/s  (1.246s,  822.14/s)  LR: 1.000e-06  Data: 0.015 (0.046)
Acc@1:  0.0000 ( 0.1054)  Acc@5:  0.4883 ( 0.5368)
Train: 0 [ 200/1251 ( 16%)]  Loss:  6.911752 (6.9155)  Time: 1.105s,  926.45/s  (1.210s,  846.22/s)  LR: 1.000e-06  Data: 0.019 (0.040)`

This makes me very confused and I am looking forward to your reply. Thanks a lot！

**Comment by yehuitang** [comment]
Thanks for you attention about our work. How many GPUs did you use when training the model?

**Comment by discaptain** [comment]
I used 1 node (8 GPUs).  Thanks for your reply!

**Comment by discaptain** [comment]
> Thanks for you attention about our work. How many GPUs did you use when training the model?

I used 1 node (8 GPUs, A100). Thanks for your reply!

**Comment by yehuitang** [comment]
We use 8 V100 (32G) GPUs to train the model.
