### ISSUE TITLE
Wavemlp

### ISSUE THREAD

**Issue by ZHUYMGeo** [huawei-noah/CV-Backbones#87]
How to Organize data in the framework of wavemlp? What should the structure of the input data be

**Comment by yehuitang** [comment]
The standard directory structure of ImageNet is used, i.e.,

│path/to/imagenet/
├──train/
│  ├── n01440764
│  │   ├── n01440764_10026.JPEG
│  │   ├── n01440764_10027.JPEG
│  │   ├── ......
│  ├── ......
├──val/
│  ├── n01440764
│  │   ├── ILSVRC2012_val_00000293.JPEG
│  │   ├── ILSVRC2012_val_00002138.JPEG
│  │   ├── ......
│  ├── ......
