### ISSUE TITLE
How can I reshape the outer token to feature map in TNT and maintain the outer dimension in feature map?

### ISSUE THREAD

**Issue by NickyXue** [huawei-noah/CV-Backbones#91]

**Comment by iamhankai** [comment]
```python
# H, W is the spatial size
B, N, C = outer_tokens.size()
feature_maps = outer_tokens[:,1:].reshape(B, H, W, C)
```

**Comment by NickyXue** [comment]
Dose it mean H and W is not the original input image H and W  because TNT has already built image patches?

**Comment by iamhankai** [comment]
In TNT, H=14, W=14.

**Comment by NickyXue** [comment]
Thanks for your prompt reply. But I'm still confused about this figure. Size of these feature maps look the same as the input.
![image](https://user-images.githubusercontent.com/95919850/167567786-1c58e680-d332-4fd4-8f73-a0527b65d5f8.png)

**Comment by iamhankai** [comment]
OK. As stated in our paper, the input image is resized into 1000x1000 for better visualization.
