### ISSUE TITLE
pretrained

### ISSUE THREAD

**Issue by 377fsq** [huawei-noah/CV-Backbones#92]
请问是否可以提供一下PyramidTNT的预训练权重？

**Comment by iamhankai** [comment]
提供了啊。。

**Comment by 377fsq** [comment]
非常打扰，原谅来自初学者的冒昧，我想问是否能提供.pth的格式预训练权重。

**Comment by iamhankai** [comment]
readme里说了，百度网盘下载：
https://github.com/huawei-noah/CV-Backbones/tree/master/tnt_pytorch

**Comment by Schadenfreude-star** [comment]
> 非常打扰，原谅来自初学者的冒昧，我想问是否能提供.pth的格式预训练权重
我来回答你。这个pth.tar就是pth。用的时候直接：
       model = torch.load(r"D:\MYRESEARCH\TNT\tnt_s_81.5.pth.tar")
就可以了。pth和pth.tar没有区别的，也不需要解压什么的。而且作者模型和预训练参数都在这里了，挺方便的。
