### ISSUE TITLE
When will the code and pretrain weights of vision gnn be released?

### ISSUE THREAD

**Issue by diggerdu** [huawei-noah/CV-Backbones#94]
Vision GNN is an insightful work. When will the code and pretrain weights of vision gnn be released?

**Comment by panda1949** [comment]
Thanks for your attention. We will release the code and pretrain weights of vision gnn as soon (in 2 weeks).

**Comment by iamhankai** [comment]
Thanks for your attention. We'll release the code and pretrain weights of vision gnn as soon (in 2 weeks).

**Comment by iamhankai** [comment]
Hi all,
It's released: https://github.com/huawei-noah/CV-Backbones/tree/master/vig_pytorch
