### ISSUE TITLE
A confusion  about the network structure of vision gnn

### ISSUE THREAD

**Issue by jx6688110** [huawei-noah/CV-Backbones#95]
Vision GNN is an awesome work.But I do not know how to get a Graph Representation of Image  by code.And in  the Detailed settings of Pyramid ViG series of the paper, the structure starts with three convolution,so I'm confused about how to use convolution after getting a Graph Representation of Image.
Hope  the code and pretrain weights of vision gnn can be released.

**Comment by abhigoku10** [comment]
@jx6688110  can you refer where the source code is for this activitiy

**Comment by iamhankai** [comment]
Thanks for the attention. We maintain the HxW feature maps and also the graph connection relationship. The downsample operation is performed on the HxW feature maps.
